export const therapistsData: Record<string, any> = {
    "1": {
        id: 1,
        name: "Ps. Esteban Cancino Ancalipe",
        title: "Psicoterapeuta Clínico Senior",
        specialty: "Terapia Cognitivo-Conductual",
        school: "Harvard Medical School",
        experience: "15+ Años",
        patients: "2.400+",
        bio: "Con más de 15 años de experiencia, mi enfoque se centra en proporcionar herramientas prácticas y basadas en evidencia para superar la ansiedad y el estrés crónico. Creo firmemente que la salud mental es el pilar de una vida plena.",
        methodology: "Trabajamos en identificar los patrones de pensamiento que generan malestar, replantearlos y reemplazarlos por estrategias conductuales constructivas.",
        quote: "La claridad mental no es la ausencia de pensamientos, sino la habilidad de observar el flujo sin perderse en él.",
        image: "/terapeutas/esteban_cancino.png",
        areas: ["Ansiedad Severa", "Mindfulness", "Desarrollo Ejecutivo", "Trastornos del Sueño"],
        rating: 4.9,
        testimonials: [
            { author: "Mauricio T.", date: "Hace 1 mes", rating: 5, content: "Muy buen profesional. Me a ayudado bastante a controlar mis crisis de ansiedad, lo recomeindo totalmwnte." },
            { author: "Felipe J.", date: "Hace 2 meses", rating: 5, content: "Llevo 5 sesiones y he notado un cambio importante, es directo y te da ejercicios claros para hacer en la casa y eso me sirvio arto." },
            { author: "Andrea R.", date: "Hace 3 meses", rating: 4, content: "Excelente, al principio me costo conectarme pero el psicoloogo me tuvo paciencia y despues fluyo todo muy bien." },
            { author: "C.S.", date: "Hace 4 meses", rating: 5, content: "Mucha empatía, se nota que sabe de lo que habla. A veces se me cortaba un poco el internet en la sesion pero el capó me esperaba sin problema." }
        ]
    },
    "2": {
        id: 2,
        name: "Dra. Elena Pardo",
        title: "Especialista en Terapia Sistémica Familiar",
        specialty: "Orientación Parental y Pareja",
        school: "Universidad de Buenos Aires",
        experience: "12 Años",
        patients: "1.800+",
        bio: "Me dedico a descifrar y reconstruir los vínculos que nos forman. Mi pasión es guiar a familias y parejas hacia dinámicas de comunicación saludables, donde cada voz tiene impacto y asilo.",
        methodology: "Exploro el árbol familiar y el entorno sistémico actual para desenmarañar conflictos repetitivos, abriendo caminos a nuevas formas de apego y entendimiento mutuo.",
        quote: "No estamos rotos; a veces, solo bailamos al compás de una música que ya no nos sirve.",
        image: "/terapeutas/paola_arriagada.jpg",
        areas: ["Terapia de Pareja", "Conflictos Familiares", "Apego", "Crisis Vitales"],
        rating: 5.0,
        testimonials: [
            { author: "Verónica L.", date: "Hace 2 semanas", rating: 5, content: "La mejor psícologa que he tenido. Es muy cálida y te hace sentir qe no estás loca por lo que sientes." },
            { author: "Camila Díaz", date: "Hace 1 mes", rating: 5, content: "Llegué super mal por un termino de relacion y la Pao me ha contenid mucho. Infinitas gracias." },
            { author: "J. P. Gutierrez", date: "Hace 3 meses", rating: 5, content: "Atencion puntual y muy profesional, 100% recomendable a cualquiera que este dudando ir a terapia." },
            { author: "Marta S.", date: "Hace 5 meses", rating: 5, content: "muy amorosa, explica todo clarito y la verdad e avansado mucho en mis trancas." },
            { author: "Ignacio M.", date: "Hace 6 meses", rating: 5, content: "Excelete profesional, me dio el espacio para desahogarme sin sentirme juzgado." },
            { author: "Daniela", date: "Hace 8 meses", rating: 5, content: "Me daba susto empazar terapia online pero paola es un sol, te alluda demacido" }
        ]
    },
    "3": {
        id: 3,
        name: "Lic. Marcos Sierra",
        title: "Psicólogo Humanista Intrapersonal",
        specialty: "Desarrollo Personal y Logoterapia",
        school: "Pontificia Universidad Católica",
        experience: "8 Años",
        patients: "900+",
        bio: "Acompaño en procesos de búsqueda de sentido, ayudando a las personas a reconectar con su propósito y superar crisis existenciales. Creo en el inmenso potencial humano latente en cada individuo.",
        methodology: "Un espacio de aceptación incondicional donde a través del diálogo profundo, la arteterapia y la introspección, facilitamos tu renacimiento emocional.",
        quote: "El mayor descubrimiento no es encontrar nuevas tierras, sino ver con nuevos ojos.",
        image: "/terapeutas/manuel_erlandsen.jpg",
        areas: ["Depresión Leve/Moderada", "Propósito Vital", "Autoestima", "Burnout Laboral"],
        rating: 4.8,
        testimonials: [
            { author: "T.A.", date: "Hace 1 mes", rating: 5, content: "Primera vez q un psicologo me entiende el tema del TDAH sin tratar de arreglarme. Seco." },
            { author: "Raúl G.", date: "Hace 3 meses", rating: 4, content: "Buen profesional, puntual y con buena disposicion. Avces me pierdo con las tareas q me da pero le pregunto y cacha al tiro." },
            { author: "Sonia P.", date: "Hace 4 meses", rating: 5, content: "hemos avanzado harto. me cuesta hablara veses pero manuel te da elt iempo nesesario." },
            { author: "Diego V.", date: "Hace 5 meses", rating: 5, content: "Cuesta encontrar a alguien especialista en neurodivergencias, súper acertado." },
            { author: "Jorge", date: "Hace 6 meses", rating: 4, content: "buena dispocicion, aunque las seciones se acian un poco cortas." }
        ]
    },
    "4": {
        id: 4,
        name: "Ps. Oliver Arancibia López",
        title: "Psicoterapia para Adultos",
        specialty: "Ansiedad generalizada, Problemas de pareja",
        school: "Universidad de Chile",
        experience: "7 Años",
        patients: "800+",
        bio: "Trabajamos en la reestructuración de la ansiedad y conflictos vinculares, buscando que cada persona o pareja encuentre sus propias herramientas.",
        methodology: "Diálogo constructivo y metas cortas para aliviar el malestar agudo rápidamente, para luego explorar las causas más profundas.",
        quote: "La comunicación es la distancia más corta entre dos personas.",
        image: "/terapeutas/oliver_arancibia.png",
        areas: ["Pareja", "Duelo", "TCA", "Disfunciones sexuales"],
        rating: 4.9,
        testimonials: [
            { author: "C. y M.", date: "Hace 2 semanas", rating: 5, content: "Fuimos por terapia de pareja y nos a servido bastante para dejar de peliar por tonteras." },
            { author: "Benjamín A.", date: "Hace 1 mes", rating: 5, content: "Tenia depre y oliver me tiro pa ariba super rápido, es muy proactivo en las sesioens." },
            { author: "P.R.", date: "Hace 2 meses", rating: 5, content: "Execelente doc, me siento muy comod con el." },
            { author: "Natalia O.", date: "Hace 4 meses", rating: 5, content: "Muy amable, tiene buena escucha y el formato online no ha sido problema." },
            { author: "F. M.", date: "Hace 5 meses", rating: 4, content: "Me gusto q me dio arto materia de apollo, abeses habla un poco rapdo pero estubo bn." },
            { author: "Antonia", date: "Hace 6 meses", rating: 5, content: "Se noto su experiencia desde la preimera consulta." },
            { author: "R. Sandoval", date: "Hace 8 meses", rating: 5, content: "Oliver un grande, logramos salavar mi matrimonio" }
        ]
    },
    "5": {
        id: 5,
        name: "Ps. Francisca Pino Aragón",
        title: "Psicoterapia para Adultos",
        specialty: "Estrés, Ansiedad social, Manejo de la ira",
        school: "Universidad de Los Andes",
        experience: "6 Años",
        patients: "600+",
        bio: "Orientada a mujeres y hombres que sufren del agobio moderno, estrés crónico y ansiedad social. Promuevo la autocompasión y la reconexión con uno mismo.",
        methodology: "Terapia de aceptación y compromiso, mindfulness y estrategias concretas para calmar el sistema nervioso.",
        quote: "Ser amable contigo mismo es el primer paso para cambiar tu mundo exterior.",
        image: "/terapeutas/francisca_pino.png",
        areas: ["Estrés", "Ansiedad social", "Duelo", "Crianza"],
        rating: 4.7,
        testimonials: [
            { author: "K.V.", date: "Hace 1 semana", rating: 5, content: "La fran es muy tierna. me ha aliviado un monton la anciedad en el tranajo." },
            { author: "Josefina U.", date: "Hace 3 semanas", rating: 4, content: "Buena terapeuta. Tuvimos un enredo con la hr una vez pero lo arreglamos altiro." },
            { author: "Lorena M.", date: "Hace 1 mes", rating: 5, content: "Me daba miedo la terapia pero ella me hizo sentir súper acojida desdel 1er dia." },
            { author: "H.T.", date: "Hace 3 meses", rating: 4, content: "He avanzado, se demora a vces en mandar los test pero da buenas erramientas." },
            { author: "Susana", date: "Hace 5 meses", rating: 5, content: "es escelente pa kienes no sabemos meditar ni relagarnos" }
        ]
    },
    "6": {
        id: 6,
        name: "Ps. Juan Rojas Pardo",
        title: "Psicoterapia para Adultos",
        specialty: "Depresión, Ansiedad, Relaciones conflictivas",
        school: "Universidad Mayor",
        experience: "9 Años",
        patients: "1.100+",
        bio: "Apoyo terapéutico comprensivo y directo. Me enfoco en desestancar procesos anímicos severos y patrones conflictivos en las relaciones.",
        methodology: "Intervenciones centradas en soluciones y reestructuración cognitiva para recuperar la vitalidad.",
        quote: "No hay oscuridad que aguante cuando decides encender tu propia luz.",
        image: "/terapeutas/juan_rojas.png",
        areas: ["Depresión", "Ansiedad", "Ideación Suicida", "Inseguridades"],
        rating: 5.0,
        testimonials: [
            { author: "Carlos", date: "Hace 2 semanas", rating: 5, content: "Estaba en un hoyo y literlamente salvó mi vida. Totalmente rwcomendable." },
            { author: "S.F.", date: "Hace 1 mes", rating: 5, content: "Muy asertivo, va directo al punto pero sin ser descortez. Me ayudo arto a subir mi autoestima." },
            { author: "Matías", date: "Hace 2 meses", rating: 5, content: "Juan cacha de lejos el problema, es seco." },
            { author: "Paula E.", date: "Hace 4 meses", rating: 5, content: "Un 7 como porfesional. Atiende a la hra, es respetuoso y no te juzga." },
            { author: "G.H.", date: "Hace 5 meses", rating: 5, content: "Excelente, logré salir de una relacion súper tóxica gracia a las cesiones." },
            { author: "Victor O.", date: "Hace 6 meses", rating: 5, content: "Muy buena dispocision siempre, contesta los wasaps super rrapido." },
            { author: "P. Muñoz", date: "Hace 7 meses", rating: 5, content: "el mejor sin duda alguna, estoi felíz" },
            { author: "Andrea", date: "Hace 8 meses", rating: 5, content: "Excelente proseso" }
        ]
    },
    "7": {
        id: 7,
        name: "Ps. Marlene Calvete Chavarría",
        title: "Psicoterapia para Adultos",
        specialty: "Trastornos de Conducta Alimentaria, Depresión",
        school: "Universidad Diego Portales",
        experience: "11 Años",
        patients: "1.500+",
        bio: "Especialista en imagen corporal y trastornos afectivos. Trabajo para que dejes de pelear con tu cuerpo y tu mente, sanando tu relación con la alimentación y contigo misma.",
        methodology: "Abordaje integral no peso-centrista acompañado de herramientas para el manejo agudo de crisis de pánico.",
        quote: "Tu valor no se mide en números ni en tallas, se mide en tu capacidad de brillar.",
        image: "/terapeutas/marlene_calvete.png",
        areas: ["TCA", "Depresión", "Crisis de Pánico", "Sueño"],
        rating: 4.8,
        testimonials: [
            { author: "Fran.", date: "Hace 1 mes", rating: 5, content: "Maravillosa, me enseno a mirarme al espejo denuevo sin llorar." },
            { author: "B.R.", date: "Hace 2 meses", rating: 4, content: "muy comprensiva, hemos avnsado re bien cn mis atakes de panico. A veses se extiende la sesion un poco pero para mi no ah sio problema." },
            { author: "Macarena L.", date: "Hace 4 meses", rating: 5, content: "Excelente profecional. Recomiendo." },
            { author: "L.M.", date: "Hace 5 meses", rating: 5, content: "Cercana, me ha servido para ordenat mi vida y perdonarme." },
            { author: "Caro T.", date: "Hace 7 meses", rating: 4, content: "tuvimos un problema por el sum  una vez,  fuera de esoo me pareci rebuena" }
        ]
    },
    "8": {
        id: 8,
        name: "Ps. Verónica Cuadra Valenzuela",
        title: "Psicoterapia para Adultos",
        specialty: "Estrés, Ansiedad social, Pareja",
        school: "Universidad C. de Chile",
        experience: "14 Años",
        patients: "2.100+",
        bio: "Amplia experiencia apoyando en procesos de adaptación, duelos complejos y manejo avanzado del estrés profesional e interpersonal.",
        methodology: "Intervenciones narrativas sistémicas, reescribiendo la historia para encontrar nuevos significados de resiliencia.",
        quote: "El dolor es inevitable, el sufrimiento prolongado es opcional cuando encontramos con quien compartirlo.",
        image: "/terapeutas/veronica_cuadra.png",
        areas: ["Estrés", "Autoestima", "Duelo", "Psicoeducación"],
        rating: 4.9,
        testimonials: [
            { author: "Patricio.", date: "Hace 2 semanas", rating: 5, content: "La mejor psiiícologa despues de provar con 3 antes, es muy clara en sus cosas." },
            { author: "M.C.", date: "Hace 3 semanas", rating: 5, content: "Perdi a mi papa y me ayudo muchisimo en todo el duelo, no c k haria sin ella." },
            { author: "Constanza D.", date: "Hace 2 meses", rating: 5, content: "Estresadisima por la pega y ahora puedo dormir wn !! la reocomiendo 100%." },
            { author: "E.J.", date: "Hace 5 meses", rating: 5, content: "muy puntual y seca. se toma enceryo lo q uno le cuenta." },
            { author: "Ricardo F.", date: "Hace 6 meses", rating: 5, content: "Un antes y un despue. Muy contenenedora." },
            { author: "Sonia G.", date: "Hace 8 meses", rating: 4, content: "avances lenteitos pero sguros, me gusto arto la atencion que entrega, se nota  k sabe pór ls arto años de exprienca" }
        ]
    }
};
