-- Actualización de esquema para mejoras de calendario
ALTER TABLE public.pacientes ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE public.pacientes ADD COLUMN IF NOT EXISTS session_link TEXT;

-- Tabla para bloqueos de días (Vacaciones, emergencias, etc)
CREATE TABLE IF NOT EXISTS public.bloqueos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    therapist_id BIGINT REFERENCES public.terapeutas(id),
    blocked_date DATE NOT NULL,
    reason TEXT
);

-- Índice para búsqueda rápida de bloqueos
CREATE INDEX IF NOT EXISTS idx_bloqueos_therapist_date ON public.bloqueos (therapist_id, blocked_date);
